version: "3.7"

networks:
  web:
    external: true
    internal:
      external: false
      driver: bridge

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/docker/caddy/data:/data
      - ~/docker/caddy/config:/config
    networks:
      - web
      - internal
