version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "80:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/music"
      ND_PLAYLISTSPATH: "_PLAYLISTS"
    volumes:
      - "/home/tony/docker/navidrome:/data"
      - "/home/tony/Dropbox/music:/music:ro"

